
const products = [
  {
    id: 1,
    category: "women",
    name: "Shiny Dress Test",
    views: "4.1k",
    price: 95.5,
    discount: 20,
    star_rating: 1.5,
    describtion: "Elegant shiny dress perfect for evening parties.",
    size: "m",
    img_url: "",
    shop:false,
  },
  {
    id: 2,
    category: "women",
    name: "Long Dress",
    views: "2.3k",
    price: 120,
    discount: 0,
    star_rating: 4.2,
    describtion: "Stylish and comfortable long dress for casual outings.",
    size: "l",
    img_url: "",
    shop:false,
  },
  {
    id: 3,
    category: "women",
    name: "Full Sweater",
    views: "3.8k",
    price: 78,
    discount: 10,
    star_rating: 4.5,
    describtion: "Warm full sweater ideal for cold seasons.",
    size: "m",
    img_url: "",
    shop:false,
  },
  {
    id: 4,
    category: "women",
    name: "White Dress",
    views: "5.2k",
    price: 110,
    discount: 25,
    star_rating: 4.8,
    describtion: "Elegant white dress suitable for formal occasions.",
    size: "m",
    img_url: "",
    shop:false,
  },
  {
    id: 5,
    category: "women",
    name: "Colorful Dress",
    views: "1.9k",
    price: 89,
    discount: 0,
    star_rating: 3.9,
    describtion: "Vibrant colorful dress for a cheerful look.",
    size: "l",
    img_url: "",
    shop:false,
  },
  {
    id: 6,
    category: "women",
    name: "White Shirt",
    views: "4.5k",
    price: 60,
    discount: 0,
    star_rating: 4.0,
    describtion: "Classic white shirt for everyday and office wear.",
    size: "m",
    img_url: "",
    shop:false,
  },
  {
    id: 7,
    category: "men",
    name: "Black Leather Jacket",
    views: "3.2k",
    price: 150,
    discount: 20,
    star_rating: 4.6,
    describtion:
      "Stylish black leather jacket perfect for winter and casual wear.",
    size: "l",
    img_url: "",
    shop:false,
  },
  {
    id: 8,
    category: "men",
    name: "Formal Blue Shirt",
    views: "2.1k",
    price: 65,
    discount: 0,
    star_rating: 4.3,
    describtion: "Smart blue shirt ideal for formal events and office wear.",
    size: "m",
    img_url: "",
    shop:false,
  },
  {
    id: 9,
    category: "men",
    name: "Casual Hoodie",
    views: "4.9k",
    price: 80,
    discount: 5,
    star_rating: 4.7,
    describtion: "Comfortable hoodie for casual days and relaxed outfits.",
    size: "xl",
    img_url: "",
    shop:false,
  },
];




[
  {
    id: 10,
    name: "Rounded Red Hat",
    category: "women",
    views: "4.9k",
    price: 80,
    discount: 5,
    star_rating: 4.7,
    describtion: "A bold and stylish red hat perfect for sunny outings or casual street looks.",
    size: "xl",
    img_url: "",
    shop:true,
  },
  {
    id: 11,
    name: "Linen-blend Shirt",
    category: "women",
    views: "4.9k",
    price: 80,
    discount: 5,
    star_rating: 4.7,
    describtion: "Lightweight linen-blend shirt ideal for breezy summer days and casual layering.",
    size: "xl",
    img_url: "",
    shop:true,
  },
  {
    id: 12,
    name: "Long-sleeve Coat",
    category: "women",
    views: "4.9k",
    price: 80,
    discount: 5,
    star_rating: 4.7,
    describtion: "Elegant and warm coat designed for chilly evenings and timeless sophistication.",
    size: "xl",
    img_url: "",
    shop:true,
  },
  {
    id: 13,
    name: "Boxy Denim Hat",
    category: "women",
    views: "4.9k",
    price: 80,
    discount: 5,
    star_rating: 4.7,
    describtion: "A casual denim hat with a boxy shape, adding flair to any relaxed outfit.",
    size: "xl",
    img_url: "",
    shop:true,
  },
  {
    id: 14,
    name: "Linen Plain Top",
    category: "women",
    views: "4.9k",
    price: 80,
    discount: 5,
    star_rating: 4.7,
    describtion: "Minimalist linen top that pairs effortlessly with jeans or skirts for everyday wear.",
    size: "xl",
    img_url: "",
    shop:true,
  },
  {
    id: 15,
    name: "Oversized T-shirt",
    category: "women",
    views: "4.9k",
    price: 80,
    discount: 5,
    star_rating: 4.7,
    describtion: "A comfy oversized tee, perfect for laid-back vibes and effortless style.",
    size: "xl",
    img_url: "",
    shop:true,
  },
  {
    id: 16,
    name: "Polarised Sunglasses",
    category: "women",
    views: "4.9k",
    price: 80,
    discount: 5,
    star_rating: 4.7,
    describtion: "Trendy polarized sunglasses offering eye protection and modern appeal.",
    size: "xl",
    img_url: "",
    shop:true,
  },
  {
    id: 17,
    name: "Rockstar Jacket",
    category: "women",
    views: "4.9k",
    price: 80,
    discount: 5,
    star_rating: 4.7,
    describtion: "Edgy rockstar-inspired jacket to add a rebellious touch to your wardrobe.",
    size: "xl",
    img_url: "",
    shop:true,
  },
  {
    id: 18,
    name: "Dotted Black Dress",
    category: "women",
    views: "4.9k",
    price: 80,
    discount: 5,
    star_rating: 4.7,
    describtion: "Chic black dress with dotted pattern, ideal for casual chic or date nights.",
    size: "xl",
    img_url: "",
    shop:true,
  }
]
