
const products = [
  {
    id: 1,
    category: "women",
    name: "Shiny Dress Test",
    views: "4.1k",
    price: 95.5,
    discount: 20,
    starRating: 1.5,
    describtion: "Elegant shiny dress perfect for evening parties.",
    size: "m",
    imgUrl: "",
  },
  {
    id: 2,
    category: "women",
    name: "Long Dress",
    views: "2.3k",
    price: 120,
    discount: 0,
    starRating: 4.2,
    describtion: "Stylish and comfortable long dress for casual outings.",
    size: "l",
    imgUrl: "",
  },
  {
    id: 3,
    category: "women",
    name: "Full Sweater",
    views: "3.8k",
    price: 78,
    discount: 10,
    starRating: 4.5,
    describtion: "Warm full sweater ideal for cold seasons.",
    size: "m",
    imgUrl: "",
  },
  {
    id: 4,
    category: "women",
    name: "White Dress",
    views: "5.2k",
    price: 110,
    discount: 25,
    starRating: 4.8,
    describtion: "Elegant white dress suitable for formal occasions.",
    size: "m",
    imgUrl: "",
  },
  {
    id: 5,
    category: "women",
    name: "Colorful Dress",
    views: "1.9k",
    price: 89,
    discount: 0,
    starRating: 3.9,
    describtion: "Vibrant colorful dress for a cheerful look.",
    size: "l",
    imgUrl: "",
  },
  {
    id: 6,
    category: "women",
    name: "White Shirt",
    views: "4.5k",
    price: 60,
    discount: 0,
    starRating: 4.0,
    describtion: "Classic white shirt for everyday and office wear.",
    size: "m",
    imgUrl: "",
  },
  {
    id: 7,
    category: "men",
    name: "Black Leather Jacket",
    views: "3.2k",
    price: 150,
    discount: 20,
    starRating: 4.6,
    describtion:
      "Stylish black leather jacket perfect for winter and casual wear.",
    size: "l",
    imgUrl: "",
  },
  {
    id: 8,
    category: "men",
    name: "Formal Blue Shirt",
    views: "2.1k",
    price: 65,
    discount: 0,
    starRating: 4.3,
    describtion: "Smart blue shirt ideal for formal events and office wear.",
    size: "m",
    imgUrl: "",
  },
  {
    id: 9,
    category: "men",
    name: "Casual Hoodie",
    views: "4.9k",
    price: 80,
    discount: 5,
    starRating: 4.7,
    describtion: "Comfortable hoodie for casual days and relaxed outfits.",
    size: "xl",
    imgUrl: "",
  },
];
